automi:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------


  # HEAD
  head_pan_position_controller:
    type: position_controllers/JointPositionController
    joint: head_pan
    pid: {p: 100.0, i: 0.01, d: 10.0}

  head_tilt_position_controller:
    type: position_controllers/JointPositionController
    joint: head_tilt
    pid: {p: 100.0, i: 0.01, d: 10.0}


  # ARMS

  r_shoulder_r_position_controller:
    type: position_controllers/JointPositionController
    joint: r_shoulder_r
    pid: {p: 100.0, i: 0.01, d: 10.0}

  r_shoulder_p_position_controller:
    type: position_controllers/JointPositionController
    joint: r_shoulder_p
    pid: {p: 100.0, i: 0.01, d: 10.0}

  r_elbow_position_controller:
    type: position_controllers/JointPositionController
    joint: r_elbow
    pid: {p: 100.0, i: 0.01, d: 10.0}

  l_shoulder_r_position_controller:
    type: position_controllers/JointPositionController
    joint: l_shoulder_r
    pid: {p: 100.0, i: 0.01, d: 10.0}

  l_shoulder_p_position_controller:
    type: position_controllers/JointPositionController
    joint: l_shoulder_p
    pid: {p: 100.0, i: 0.01, d: 10.0}

  l_elbow_position_controller:
    type: position_controllers/JointPositionController
    joint: l_elbow
    pid: {p: 100.0, i: 0.01, d: 10.0}



  # LEGS

  r_hip_y_position_controller:
    type: position_controllers/JointPositionController
    joint: r_hip_y
    pid: {p: 100.0, i: 0.01, d: 10.0}



  r_hip_r_position_controller:
    type: position_controllers/JointPositionController
    joint: r_hip_r
    pid: {p: 100.0, i: 0.01, d: 10.0}



  r_hip_p_position_controller:
    type: position_controllers/JointPositionController
    joint: r_hip_p
    pid: {p: 100.0, i: 0.01, d: 10.0}



  r_knee_position_controller:
    type: position_controllers/JointPositionController
    joint: r_knee
    pid: {p: 100.0, i: 0.01, d: 10.0}



  r_ankle_r_position_controller:
    type: position_controllers/JointPositionController
    joint: r_ankle_r
    pid: {p: 100.0, i: 0.01, d: 10.0}



  r_ankle_p_position_controller:
    type: position_controllers/JointPositionController
    joint: r_ankle_p
    pid: {p: 100.0, i: 0.01, d: 10.0}



  l_hip_y_position_controller:
    type: position_controllers/JointPositionController
    joint: l_hip_y
    pid: {p: 100.0, i: 0.01, d: 10.0}



  l_hip_r_position_controller:
    type: position_controllers/JointPositionController
    joint: l_hip_r
    pid: {p: 100.0, i: 0.01, d: 10.0}



  l_hip_p_position_controller:
    type: position_controllers/JointPositionController
    joint: l_hip_p
    pid: {p: 100.0, i: 0.01, d: 10.0}



  l_knee_position_controller:
    type: position_controllers/JointPositionController
    joint: l_knee
    pid: {p: 100.0, i: 0.01, d: 10.0}



  l_ankle_r_position_controller:
    type: position_controllers/JointPositionController
    joint: l_ankle_r
    pid: {p: 100.0, i: 0.01, d: 10.0}



  l_ankle_p_position_controller:
    type: position_controllers/JointPositionController
    joint: l_ankle_p
    pid: {p: 100.0, i: 0.01, d: 10.0}
